### ISSUE TITLE
command 'materialTheme.setAccent' not found

### ISSUE THREAD

**Issue by hazcod** [material-theme/vsc-material-theme#381]
**Describe the bug**
Trying to set the accent color on macOS latest VSCode will result in error `command 'materialTheme.setAccent' not found`.

**To Reproduce**
1. `rm -rf ~/.vscode/extensions`
2. Install `Material theme`
3. `Change accent color`
4. Error pops up.

**Additional context**
No logs related to any error.

**Comment by LasaleFamine** [comment]
Hi @hazcod this is actually strange. I need some more days to investigate.

**Comment by equinusocio** [comment]
Closed due inactivity

**Comment by hazcod** [comment]
Reopen since it was being investigated?

**Comment by equinusocio** [comment]
We can't replicate the issue and we think the `rm -rf ~/.vscode/extensions` is not a common scenario that require to much time to investigate on. We are focused on more important issues right now, and, unless this issue will become a common (other people report it), we have to close it, for now.

**Comment by cozyGalvinism** [comment]
I get the same error, I'm running VS Code 1.39.1.

**Comment by eigoor** [comment]
I get the same error. I tried to uninstall/reinstall the extension.
In the logs I can see that the activation fails.

```
[2020-01-09 09:33:33.078] [exthost] [info] ExtensionService#_doActivateExtension Equinusocio.vsc-material-theme {"startup":false,"extensionId":{"value":"Equinusocio.vsc-material-theme","_lower":"equinusocio.vsc-material-theme"},"activationEvent":"*"}
[2020-01-09 09:33:33.078] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/julian/.vscode/extensions/equinusocio.vsc-material-theme-31.12.0/build/material.theme.config
[2020-01-09 09:33:33.092] [exthost] [error] Activating extension Equinusocio.vsc-material-theme failed due to an error:
[2020-01-09 09:33:33.095] [exthost] [error] TypeError: Cannot read property 'firstInstall' of undefined
	at /home/julian/.vscode/extensions/equinusocio.vsc-material-theme-31.12.0/build/material.theme.config.js:28:31
	at Generator.next (<anonymous>)
	at /home/julian/.vscode/extensions/equinusocio.vsc-material-theme-31.12.0/build/material.theme.config.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/home/julian/.vscode/extensions/equinusocio.vsc-material-theme-31.12.0/build/material.theme.config.js:4:12)
	at activate (/home/julian/.vscode/extensions/equinusocio.vsc-material-theme-31.12.0/build/material.theme.config.js:25:12)
	at Function._callActivateOptional (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:911)
	at Function._callActivate (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:562)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:694:651
	at async Promise.all (index 0)
	at async d.$activate (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:710)
```

**Comment by LasaleFamine** [comment]
Hi all, this is related to old versions of VSCode. Please update VSCode to the latest version and everything should be working fine.

**Comment by eigoor** [comment]
Hi, I'm using version 1.41.1 of VSCode. From what I can see that is the latest stable version.
```
julian ~> code --version
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64
```

Or do you mean VSCode insiders?

**Comment by LasaleFamine** [comment]
That's the correct latest version. I think here we are facing another problem and I seriously think this is related to #414. What OS you are on? Seems like we loaded an undefined config. Eventually, would you mind add you problem to that issue? So we can track down from there.

**Comment by eigoor** [comment]
I'm running Arch Linux and have installed VSCode from the AUR.

For me it looks more like you have a possible race condition. In your `core/extension-manager.ts` you call in the constructor `this.init()`. But init is an async function so your exported ExtensionManger (which you use in `material.theme.config.ts` to access firstInstall) does not necessarily everything correctly initialized because init has not finished.

I did a quick test and awaiting `extensionManager.init()` (need to make it public) before line 13 of `material.theme.config.ts` seems to fix the problem.

**Comment by LasaleFamine** [comment]
Ouch! Nice carch! Would you like to open a PR?
